/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Beans/Customizer.java to edit this template
 */
package View;

import Constants.Paging_values;
import Constants.Response_code;
import Control.Controller;
import Formatters.Table_configurator;
import Models.Response;
import java.util.ArrayList;
import javax.swing.JPanel;

/**
 *
 * @author memis
 */
public class get_available_vehicles extends javax.swing.JPanel implements java.beans.Customizer {
    
    private Object bean;
    
    private int total_pages;
    private int current_page = 1;
    private ArrayList<Integer> vehicle_id = new ArrayList<>();
    
    private void configure_paging(){
        int persons_count = Controller.get_vehicle_count();
        total_pages = Math.ceilDiv(persons_count, Paging_values.vehicle_paging);
        if (total_pages == 0){
            total_pages = 1;
        }
    }
    
    private void get_page(){
        vehicle_id.clear();
        Response response = Controller.get_vehicle(Paging_values.vehicle_paging * current_page - Paging_values.vehicle_paging + 1, Paging_values.vehicle_paging * current_page);
        if (response.getResponse_code() == Response_code.SUCCESS){
            ArrayList<String> data = (ArrayList) response.getResponse_content();
            ArrayList<String> dataFiltered = new ArrayList<>();
            vehicle_id.add(Integer.valueOf(data.get(0)));
            for (int i = 0; i < data.size(); i+=1){ 
                dataFiltered.add(data.get(i));               
            }
            String[] header = {"Seat Quantity", "Brand", "Model", "Color", "Plate number"};
            TB_vehicle = Table_configurator.setData(TB_vehicle, header, dataFiltered);
        }
    }

    /**
     * Creates new customizer get_available_vehicles
     */
    public get_available_vehicles() {
        initComponents();
        configure_paging();
        
        get_page();
    }
    
    public void setObject(Object bean) {
        this.bean = bean;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the FormEditor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TB_vehicle = new javax.swing.JTable();
        BT_previous = new javax.swing.JButton();
        BT_next = new javax.swing.JButton();
        BT_go_back = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(600, 550));

        jLabel1.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setText("Available vehicles");
        jLabel1.setToolTipText("");

        TB_vehicle.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(TB_vehicle);
        TB_vehicle.getAccessibleContext().setAccessibleName("TB_vehicle");
        TB_vehicle.getAccessibleContext().setAccessibleDescription("");

        BT_previous.setBackground(new java.awt.Color(0, 0, 255));
        BT_previous.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 12)); // NOI18N
        BT_previous.setForeground(new java.awt.Color(255, 255, 255));
        BT_previous.setText("Previous");
        BT_previous.setToolTipText("");
        BT_previous.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT_previousActionPerformed(evt);
            }
        });

        BT_next.setBackground(new java.awt.Color(0, 0, 255));
        BT_next.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 12)); // NOI18N
        BT_next.setForeground(new java.awt.Color(255, 255, 255));
        BT_next.setText("Next");
        BT_next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT_nextActionPerformed(evt);
            }
        });

        BT_go_back.setBackground(new java.awt.Color(0, 0, 255));
        BT_go_back.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 12)); // NOI18N
        BT_go_back.setForeground(new java.awt.Color(255, 255, 255));
        BT_go_back.setText("Go back");
        BT_go_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT_go_backActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BT_previous)
                        .addGap(18, 18, 18)
                        .addComponent(BT_next, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(511, 511, 511)
                        .addComponent(BT_go_back))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addGap(24, 24, 24)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BT_previous)
                    .addComponent(BT_next))
                .addGap(18, 18, 18)
                .addComponent(BT_go_back)
                .addContainerGap(110, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BT_nextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT_nextActionPerformed
        if (current_page != total_pages){
            current_page += 1;
            get_page();
        }
    }//GEN-LAST:event_BT_nextActionPerformed

    private void BT_previousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT_previousActionPerformed
        if (current_page != 1){
            current_page -= 1;
            get_page();
        }
    }//GEN-LAST:event_BT_previousActionPerformed

    private void BT_go_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT_go_backActionPerformed
        JPanel driver1 = new Driver();
        Main_window.render_panel(driver1);
    }//GEN-LAST:event_BT_go_backActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BT_go_back;
    private javax.swing.JButton BT_next;
    private javax.swing.JButton BT_previous;
    private javax.swing.JTable TB_vehicle;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
