/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Beans/Customizer.java to edit this template
 */
package View;

import Constants.Response_code;
import Control.Controller;
import Models.Response;
import Models.Vehicle;
import java.awt.Color;

/**
 *
 * @author memis
 */
public class Insert_vehicle_panel extends javax.swing.JPanel implements java.beans.Customizer {
    
    private Object bean;

    /**
     * Creates new customizer Insert_vehicle_panel
     */
    public Insert_vehicle_panel() {
        initComponents();
    }
    
    private void clean_fields(){
        SP_seats.setValue(0);
        FT_brand.setText("");
        FT_car_model.setText("");
        FT_color.setText("");
        FT_plate_number.setText("");
    }
    
    public void setObject(Object bean) {
        this.bean = bean;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the FormEditor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        FT_brand = new javax.swing.JTextField();
        FT_car_model = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        FT_color = new javax.swing.JTextField();
        FT_plate_number = new javax.swing.JTextField();
        BT_register = new javax.swing.JButton();
        BT_go_back = new javax.swing.JButton();
        LB_output_message = new javax.swing.JLabel();
        SP_seats = new javax.swing.JSpinner();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(600, 550));

        jLabel1.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setText("Register Vehicle");

        jLabel2.setText("Brand:");

        jLabel3.setText("Car Model:");

        jLabel4.setText("Seat quantity:");

        FT_car_model.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FT_car_modelActionPerformed(evt);
            }
        });

        jLabel5.setText("Color:");

        jLabel6.setText("Plate_number:");

        BT_register.setBackground(new java.awt.Color(0, 0, 255));
        BT_register.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 12)); // NOI18N
        BT_register.setForeground(new java.awt.Color(255, 255, 255));
        BT_register.setText("Register");
        BT_register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT_registerActionPerformed(evt);
            }
        });

        BT_go_back.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 12)); // NOI18N
        BT_go_back.setText("Go back");
        BT_go_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT_go_backActionPerformed(evt);
            }
        });

        LB_output_message.setText(" ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(FT_color, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(BT_register)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(BT_go_back))
                            .addComponent(LB_output_message, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel3))
                                    .addComponent(jLabel1))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(FT_brand, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel5))
                                    .addGap(25, 25, 25)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(FT_car_model)
                                        .addComponent(FT_plate_number, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                                        .addComponent(jLabel6)))))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(SP_seats, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(194, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FT_brand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FT_car_model, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SP_seats, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FT_color, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FT_plate_number, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BT_register)
                    .addComponent(BT_go_back))
                .addGap(18, 18, 18)
                .addComponent(LB_output_message)
                .addContainerGap(194, Short.MAX_VALUE))
        );

        FT_brand.getAccessibleContext().setAccessibleName("FT_brand");
        FT_car_model.getAccessibleContext().setAccessibleName("FT_car_model");
        FT_color.getAccessibleContext().setAccessibleName("FT_color");
        FT_plate_number.getAccessibleContext().setAccessibleName("FT_plate_number");
        FT_plate_number.getAccessibleContext().setAccessibleDescription("");
    }// </editor-fold>//GEN-END:initComponents

    private void FT_car_modelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FT_car_modelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FT_car_modelActionPerformed

    private void BT_registerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT_registerActionPerformed
                
        Vehicle ride = new Vehicle((int)SP_seats.getValue(), FT_brand.getText(), FT_car_model.getText(), FT_color.getText(), FT_plate_number.getText());
        
        Response response = Controller.register_vehicle(ride);
        
        LB_output_message.setText(response.getMessage());
        LB_output_message.setForeground(Color.red);
        if (response.getResponse_code() == Response_code.SUCCESS){
            LB_output_message.setForeground(Color.black);
            clean_fields();
        }
        LB_output_message.setVisible(true);
    }//GEN-LAST:event_BT_registerActionPerformed

    private void BT_go_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT_go_backActionPerformed
        Main_window.goBack();
    }//GEN-LAST:event_BT_go_backActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BT_go_back;
    private javax.swing.JButton BT_register;
    private javax.swing.JTextField FT_brand;
    private javax.swing.JTextField FT_car_model;
    private javax.swing.JTextField FT_color;
    private javax.swing.JTextField FT_plate_number;
    private javax.swing.JLabel LB_output_message;
    private javax.swing.JSpinner SP_seats;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
