package View;

import java.awt.BorderLayout;
import java.awt.Component;
import java.awt.Dimension;
import java.util.Stack;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author memis
 */
public class Main_window extends javax.swing.JFrame {
    
    private static Stack<JPanel> panelStack = new Stack<>();
    private JScrollPane scrollPane;

    
    public static void render_panel(JPanel panel){
        
        if (content_panel.getComponentCount() > 0) {
        Component currentComponent = content_panel.getComponent(0);
            if (currentComponent instanceof JPanel) {
                panelStack.push((JPanel) currentComponent); // Push the current panel onto the stack
            }
        }
        
        
        content_panel.removeAll();                             
        content_panel.add(panel,BorderLayout.CENTER); 
        content_panel.revalidate();
        content_panel.repaint();
        
        JFrame frame = (JFrame) SwingUtilities.getWindowAncestor(content_panel);
        if (frame != null) {
            frame.pack();
        }
    }
    
    public static void goBack() {
         if (!panelStack.isEmpty()) {
            JPanel previousPanel = panelStack.pop(); // Pop the last panel from the stack
            render_panel(previousPanel); // Render the previous panel
        } else {
            System.out.println("No previous panel to go back to."); // Debugging statement
        }
    }

    public Main_window() {
        initComponents();
        this.setTitle("UniDrive_carpooling");
        content_panel.setLayout(new BorderLayout());
        
        scrollPane = new JScrollPane(content_panel); // Create JScrollPane and wrap content_panel
        scrollPane.setVerticalScrollBarPolicy(JScrollPane.VERTICAL_SCROLLBAR_ALWAYS);
        scrollPane.setHorizontalScrollBarPolicy(JScrollPane.HORIZONTAL_SCROLLBAR_NEVER);

        // Set the layout for the main frame
        getContentPane().setLayout(new BorderLayout());
        getContentPane().add(scrollPane, BorderLayout.CENTER);
        
        JPanel login_panel = new Login_panel();
        render_panel(login_panel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        content_panel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(600, 500));

        content_panel.setBackground(new java.awt.Color(255, 255, 255));
        content_panel.setMinimumSize(new java.awt.Dimension(600, 550));
        content_panel.setPreferredSize(new java.awt.Dimension(600, 550));

        javax.swing.GroupLayout content_panelLayout = new javax.swing.GroupLayout(content_panel);
        content_panel.setLayout(content_panelLayout);
        content_panelLayout.setHorizontalGroup(
            content_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        content_panelLayout.setVerticalGroup(
            content_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 550, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(content_panel, javax.swing.GroupLayout.DEFAULT_SIZE, 660, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(content_panel, javax.swing.GroupLayout.DEFAULT_SIZE, 550, Short.MAX_VALUE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        content_panel.getAccessibleContext().setAccessibleName("");

        getAccessibleContext().setAccessibleName("Login");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {


        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main_window().setVisible(true);
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private static javax.swing.JPanel content_panel;
    // End of variables declaration//GEN-END:variables
}
