/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Beans/Customizer.java to edit this template
 */
package View;

import Constants.Response_code;
import Control.Controller;
import Models.Response;
import Models.Route;
import java.awt.Color;
import java.sql.Timestamp;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.LocalTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import javax.swing.JPanel;

/**
 *
 * @author memis
 */
public class Route_panel extends javax.swing.JPanel implements java.beans.Customizer {
    
    private Object bean;
    
    private String get_plate;
    
    private void clean_fields(){
        FF_date.setText("");
        FF_start.setText("");
        FF_end.setText("");
        SP_space.setValue(0);
        CB_payment.setSelectedIndex(0);
        FF_amount.setText("");
        FT_starting_point.setText("");
        FT_main_point.setText("");
        FT_spot_1.setText("");
        FT_spot_2.setText("");
        CB_end_point.setSelectedIndex(0);
    }

    /**
     * Creates new customizer Route
     */
    public Route_panel() {
        initComponents();
        
        Response response = Controller.get_vehicle(1, 10);
        if (response.getResponse_code() == Response_code.SUCCESS){
            ArrayList<String> data = (ArrayList) response.getResponse_content();
            ArrayList<String> dataFiltered = new ArrayList<>();
            for (int i = 0; i < data.size(); i+=5){ 
                dataFiltered.add(data.get(i+1));
                dataFiltered.add(data.get(i+3)); 
                dataFiltered.add(data.get(i+4)); 
            }
            for(int i = 0; i < dataFiltered.size(); i+=3){
                CB_vehicle.addItem(dataFiltered.get(i) + " | " + dataFiltered.get(i+1) + " | " + dataFiltered.get(i+2));
            }
        }
        else{
            CB_vehicle.addItem("No vehicles registered");
        }
    }
    
    public void setObject(Object bean) {
        this.bean = bean;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the FormEditor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        FF_date = new javax.swing.JFormattedTextField();
        FF_start = new javax.swing.JFormattedTextField();
        FF_end = new javax.swing.JFormattedTextField();
        FT_main_point = new javax.swing.JTextField();
        FT_spot_1 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        SP_space = new javax.swing.JSpinner();
        jLabel14 = new javax.swing.JLabel();
        FT_key_1 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        FT_spot_2 = new javax.swing.JTextField();
        CB_end_point = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        BT_submit = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        CB_vehicle = new javax.swing.JComboBox<>();
        CB_payment = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        FF_amount = new javax.swing.JFormattedTextField();
        FT_starting_point = new javax.swing.JTextField();
        LB_output_message = new javax.swing.JLabel();
        BT_go_back = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setText("Route Creator");

        jLabel2.setText("Date");

        jLabel3.setText("Start time");

        jLabel4.setText("End time");

        jLabel5.setText("Starting point");

        jLabel6.setText("Main road");

        jLabel7.setText("Relevant spot 1");

        FF_date.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd-MMM-yy"))));
        FF_date.setText("dd-MON-yy");

        FF_start.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("HH:mm"))));
        FF_start.setText("HH:mm");

        FF_end.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("HH:mm"))));
        FF_end.setText("HH:mm");
        FF_end.setToolTipText("");

        jLabel9.setText("End point:");

        jLabel12.setText("Available spots");

        jLabel14.setText("Key Location");

        jLabel15.setText("Relevant spot 2");

        FT_spot_2.setActionCommand("<Not Set>");

        CB_end_point.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "TEC - Cartago", "UCR - Cartago", "UNED - Cartago", "UNA", "TEC - San José - UCR - San Pedro" }));
        CB_end_point.setToolTipText("");

        jLabel16.setText("Payment type");

        BT_submit.setBackground(new java.awt.Color(0, 0, 255));
        BT_submit.setForeground(new java.awt.Color(255, 255, 255));
        BT_submit.setText("Submit");
        BT_submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT_submitActionPerformed(evt);
            }
        });

        jLabel8.setText("Vehicle");

        CB_vehicle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CB_vehicleActionPerformed(evt);
            }
        });

        CB_payment.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Efectivo", "SINPE", "Transferencia" }));

        jLabel10.setText("Amount");

        FF_amount.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        BT_go_back.setText("Go back");
        BT_go_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT_go_backActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(223, 223, 223)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(LB_output_message, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(BT_go_back)
                                .addGap(18, 18, 18)
                                .addComponent(BT_submit))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(CB_payment, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel2)
                                    .addComponent(FF_date, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel7)
                                    .addComponent(FT_spot_1)
                                    .addComponent(jLabel8)
                                    .addComponent(CB_vehicle, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel16)
                                    .addComponent(FT_starting_point))
                                .addGap(55, 55, 55)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel12)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(FF_start, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(FT_main_point, javax.swing.GroupLayout.Alignment.LEADING))
                                            .addComponent(jLabel15)
                                            .addComponent(FT_spot_2, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(60, 60, 60)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(CB_end_point, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel9)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(jLabel4)
                                                .addComponent(FF_end, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                                                .addComponent(jLabel14)
                                                .addComponent(FT_key_1))))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(FF_amount, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(SP_space, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)))))))
                .addContainerGap(58, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FF_date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FF_start, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FF_end, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FT_main_point, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FT_key_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FT_starting_point, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel15)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FT_spot_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FT_spot_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CB_end_point, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SP_space, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CB_vehicle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CB_payment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FF_amount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BT_submit)
                    .addComponent(LB_output_message)
                    .addComponent(BT_go_back))
                .addContainerGap(90, Short.MAX_VALUE))
        );

        FF_date.getAccessibleContext().setAccessibleName("FF_date");
        FT_main_point.getAccessibleContext().setAccessibleName("TF_start_point");
        FT_spot_1.getAccessibleContext().setAccessibleName("TF_spot_1");
        SP_space.getAccessibleContext().setAccessibleName("SP_space");
        FT_key_1.getAccessibleContext().setAccessibleName("TF_key_1");
        FT_key_1.getAccessibleContext().setAccessibleDescription("");
        FT_spot_2.getAccessibleContext().setAccessibleName("TF_spot_2");
        FT_spot_2.getAccessibleContext().setAccessibleDescription("");
        CB_end_point.getAccessibleContext().setAccessibleName("CB_end_point");
        CB_vehicle.getAccessibleContext().setAccessibleName("CB_vehicle");
        CB_payment.getAccessibleContext().setAccessibleName("CB_payment");
        FF_amount.getAccessibleContext().setAccessibleName("FF_amount");
        FT_starting_point.getAccessibleContext().setAccessibleName("FT_starting_point");
        FT_starting_point.getAccessibleContext().setAccessibleDescription("");
    }// </editor-fold>//GEN-END:initComponents

    private void BT_submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT_submitActionPerformed
        String license_plate = (String)CB_vehicle.getSelectedItem();
        
        String[] parts = license_plate.split(" \\| ");

        String plate_Number = parts[parts.length - 1];
        
        DateTimeFormatter timeFormatter = DateTimeFormatter.ofPattern("HH:mm");
        
        String startTimeString = FF_start.getText();
        String endTimeString = FF_end.getText();
        
        LocalTime startTime = LocalTime.parse(startTimeString, timeFormatter);
        LocalTime endTime = LocalTime.parse(endTimeString, timeFormatter);
        
        DateTimeFormatter dateFormatter = DateTimeFormatter.ofPattern("dd-MMM-yy");
        
        LocalDate date = LocalDate.parse((FF_date.getText().trim()),dateFormatter); 
        
        LocalDateTime startDateTime = LocalDateTime.of(date, startTime);
        LocalDateTime endDateTime = LocalDateTime.of(date, endTime);
        
        Timestamp startStamp = Timestamp.valueOf(startDateTime);
        Timestamp endStamp = Timestamp.valueOf(endDateTime);
        
        Route route = new Route(FF_date.getText(),startStamp, endStamp,
                                (int)SP_space.getValue(), (String)CB_payment.getSelectedItem(),FF_amount.getText(), FT_starting_point.getText(),
                                FT_main_point.getText(), FT_spot_1.getText(), FT_spot_2.getText(), (String)CB_end_point.getSelectedItem(),plate_Number);
        
        Response response = Controller.insert_route(route);
        
        LB_output_message.setText(response.getMessage());
        LB_output_message.setForeground(Color.red);
        if (response.getResponse_code() == Response_code.SUCCESS){
            LB_output_message.setForeground(Color.black);
            clean_fields();
        }
        LB_output_message.setVisible(true);
    }//GEN-LAST:event_BT_submitActionPerformed

    private void CB_vehicleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CB_vehicleActionPerformed
        
    }//GEN-LAST:event_CB_vehicleActionPerformed

    private void BT_go_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT_go_backActionPerformed
        JPanel go_back = new Driver();
        Main_window.render_panel(go_back);
    }//GEN-LAST:event_BT_go_backActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BT_go_back;
    private javax.swing.JButton BT_submit;
    private javax.swing.JComboBox<String> CB_end_point;
    private javax.swing.JComboBox<String> CB_payment;
    private javax.swing.JComboBox<String> CB_vehicle;
    private javax.swing.JFormattedTextField FF_amount;
    private javax.swing.JFormattedTextField FF_date;
    private javax.swing.JFormattedTextField FF_end;
    private javax.swing.JFormattedTextField FF_start;
    private javax.swing.JTextField FT_key_1;
    private javax.swing.JTextField FT_main_point;
    private javax.swing.JTextField FT_spot_1;
    private javax.swing.JTextField FT_spot_2;
    private javax.swing.JTextField FT_starting_point;
    private javax.swing.JLabel LB_output_message;
    private javax.swing.JSpinner SP_space;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
