/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Beans/Customizer.java to edit this template
 */
package View;

/**
 *
 * @author memis
 */
public class User_access extends javax.swing.JPanel implements java.beans.Customizer {
    
    private Object bean;

    /**
     * Creates new customizer User_access
     */
    public User_access() {
        initComponents();
    }
    
    public void setObject(Object bean) {
        this.bean = bean;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the FormEditor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Access_frame = new javax.swing.JInternalFrame();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        username_access_tbox = new javax.swing.JTextField();
        password_access_tbox = new javax.swing.JTextField();
        sign_in_bt = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        sign_up_bt = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        Access_frame.setBackground(new java.awt.Color(204, 204, 255));
        Access_frame.setClosable(true);
        Access_frame.setIconifiable(true);
        Access_frame.setTitle("Udrive carpooling");
        Access_frame.setMinimumSize(new java.awt.Dimension(104, 40));
        Access_frame.setPreferredSize(new java.awt.Dimension(617, 440));
        Access_frame.setVerifyInputWhenFocusTarget(false);
        Access_frame.setVisible(true);
        Access_frame.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("News701 BT", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 204));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setLabelFor(Access_frame);
        jLabel1.setText("Udrive Carpooling");
        Access_frame.getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 605, -1));

        jLabel2.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 14)); // NOI18N
        jLabel2.setText("Username:");
        Access_frame.getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 240, 80, -1));

        jLabel3.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 14)); // NOI18N
        jLabel3.setText("Password:");
        Access_frame.getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 290, 80, -1));

        username_access_tbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                username_access_tboxActionPerformed(evt);
            }
        });
        Access_frame.getContentPane().add(username_access_tbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 240, 300, -1));
        username_access_tbox.getAccessibleContext().setAccessibleName("username_access_tbox");

        Access_frame.getContentPane().add(password_access_tbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 290, 300, -1));
        password_access_tbox.getAccessibleContext().setAccessibleName("password_access_tbox");

        sign_in_bt.setBackground(new java.awt.Color(0, 0, 204));
        sign_in_bt.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        sign_in_bt.setForeground(new java.awt.Color(242, 242, 242));
        sign_in_bt.setText("Sign In");
        sign_in_bt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sign_in_btActionPerformed(evt);
            }
        });
        Access_frame.getContentPane().add(sign_in_bt, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 330, 80, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI Light", 2, 10)); // NOI18N
        jLabel4.setText("Not registered yet? ->");
        Access_frame.getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 380, -1, 20));

        sign_up_bt.setBackground(new java.awt.Color(242, 242, 242));
        sign_up_bt.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 10)); // NOI18N
        sign_up_bt.setForeground(new java.awt.Color(0, 0, 204));
        sign_up_bt.setText("Sign Up");
        sign_up_bt.setToolTipText("");
        sign_up_bt.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        sign_up_bt.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Access_frame.getContentPane().add(sign_up_bt, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 380, -1, -1));

        jLabel5.setForeground(new java.awt.Color(255, 0, 51));
        jLabel5.setText("%LOGO%");
        Access_frame.getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 130, -1, 20));

        add(Access_frame, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void username_access_tboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_username_access_tboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_username_access_tboxActionPerformed

    private void sign_in_btActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sign_in_btActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sign_in_btActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JInternalFrame Access_frame;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField password_access_tbox;
    private javax.swing.JButton sign_in_bt;
    private javax.swing.JButton sign_up_bt;
    private javax.swing.JTextField username_access_tbox;
    // End of variables declaration//GEN-END:variables
}
